Repository MyUNiDAYS/StyleGuide, pull requests merged in 2018-10, with the labels that each got.

#29 JS Styleguide Enhancement
  Javascript/README.md
Labels: enhancement

#32 Add a LESS section to the main ReadMe
  README.md
Labels: docs, easy

#38 Html
  HTML/StyleGuide.cshtml
  README.md
  SQL/StyleGuide.sql
Labels: docs, easy, enhancement

#28 Swift Style Guide
  README.md
  Swift/README.md
Labels: enhancement
